#ifndef __CHARGE_CONTROLLER_H__
#define __CHARGE_CONTROLLER_H__

#include "stdint.h"

typedef enum {
  CHARGE_MASK = 0x10000000,
  LOCAL_DISCHARGE_MASK = 0x20000000,
  GLOBAL_DISCHARGE_MASK = 0x40000000,
  
  CHARGE_CONTROLLER_DO_NOTHING = 0,
  CHARGE_CONTROLLER_OFF,
  CHARGE_CONTROLLER_START_CHARGE = CHARGE_MASK,
  CHARGE_CONTROLLER_WAIT_START_CHARGE,
  CHARGE_CONTROLLER_CHARGE,
  CHARGE_CONTROLLER_STOP_CHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_CHARGE,
  CHARGE_CONTROLLER_STOP_CHARGE_FOR_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_CHARGE_FOR_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_STOP_CHARGE_FOR_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_CHARGE_FOR_GLOBAL_DISCHARGE,
  
  CHARGE_CONTROLLER_START_DIRECT_CHARGE,
  CHARGE_CONTROLLER_WAIT_START_DIRECT_CHARGE,
  CHARGE_CONTROLLER_DIRECT_CHARGE,
  CHARGE_CONTROLLER_STOP_DIRECT_CHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_DIRECT_CHARGE,
  
  CHARGE_CONTROLLER_START_LOCAL_DISCHARGE = LOCAL_DISCHARGE_MASK,
  CHARGE_CONTROLLER_WAIT_START_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_STOP_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_STOP_LOCAL_DISCHARGE_FOR_CHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_LOCAL_DISCHARGE_FOR_CHARGE,
  
  CHARGE_CONTROLLER_START_GLOBAL_DISCHARGE = GLOBAL_DISCHARGE_MASK,
  CHARGE_CONTROLLER_WAIT_START_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_PAUSE_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_PAUSE_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_GLOBAL_DISCHARGE_PAUSED,
  CHARGE_CONTROLLER_STOP_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_STOP_GLOBAL_DISCHARGE_FOR_CHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_GLOBAL_DISCHARGE_FOR_CHARGE,
  
  CHARGE_CONTROLLER_START_DIRECT_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_START_DIRECT_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_DIRECT_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_STOP_DIRECT_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_DIRECT_LOCAL_DISCHARGE,
  CHARGE_CONTROLLER_START_DIRECT_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_START_DIRECT_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_DIRECT_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_STOP_DIRECT_GLOBAL_DISCHARGE,
  CHARGE_CONTROLLER_WAIT_STOP_DIRECT_GLOBAL_DISCHARGE,

} eChargeControllerStates;

void ChargeControllerStartDischarge ();
void ChargeControllerStopDischarge ();
void ChargeControllerStartCharge ();
void ChargeControllerStopCharge ();

#endif // __CHARGE_CONTROLLER_H__
