#ifndef __CONV_CONTACTOR_CONTROLLER_H__
#define __CONV_CONTACTOR_CONTROLLER_H__

#include "stdint.h"

typedef enum {
  CONV_CONTACTOR_SET_ON,
  CONV_CONTACTOR_WAIT_ON,
  CONV_CONTACTOR_IS_ON,
  CONV_CONTACTOR_SET_OFF,
  CONV_CONTACTOR_WAIT_OFF,
  CONV_CONTACTOR_IS_OFF
} ConvContactorControllerStates;

#endif // __CONV_CONTACTOR_CONTROLLER_H__
